parameters:
    user: ~
    proxy_host: ~
    proxy_port: ~

    external_database_driver: pdo_pgsql
    external_database_host: localhost
    external_database_port: ~
    external_database_name: ~
    external_database_path: ~
    external_database_user: ~
    external_database_password: ~
    external_database_charset: UTF8

    metador_temp_dir: '%kernel.root_dir%/../var/temp/'
    metador_plugin_dir: '%kernel.root_dir%/../src/Plugins/'
    maintenance_file: '%kernel.root_dir%/../web/maintenance.php'
    operates_on_url: ''
